# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
    - README.md

pool:
  vmImage: 'windows-latest'

steps:
  - task: GitVersion@5
    inputs:
      runtime: 'core'
      configFilePath: 'GitVersion.yml'
      
  - script: echo %Action%%BuildVersion%
    displayName: 'Set build version'
    env:
      Action: '##vso[build.updatebuildnumber]'
      BuildVersion: $(GitVersion.NuGetVersionV2)

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      options: '-Drelease.version=$(GitVersion.NuGetVersionV2)'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

  - task: GitHubRelease@1
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      gitHubConnection: 'Github'
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'userSpecifiedTag'
      tag: '$(GitVersion.NuGetVersionV2)'
      title: '$(GitVersion.NuGetVersionV2)'
      assets: '$(Build.SourcesDirectory)/api-key-module/target/*.jar'
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'
    
